version: 2
jobs:
  build:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Add Dependencies
          command: apk add --no-cache curl 
      - run:
          name: install and build project wishop-app-api
          command: npm install && npm build
      - run: 
          name: Test Project
          command: echo "This Test Space"
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t huag1234/wishop-app-api:$API_TAG .
            docker push huag1234/wishop-app-api:$API_TAG
  deploy-to-dev:
    machine: true
    steps:
    # ssh without keypair
    #sshpass -p sshwishop ssh -o StrictHostKeyChecking=no wishop@54.169.236.178
      - run: 
          name: SSHpass to server
          command: | 
            sudo apt-get update
            sudo apt-get install sshpass
            sudo sshpass -p $PASS_SERVER ssh -o StrictHostKeyChecking=no $USER_SERVER@$SERVER_HOST "sudo docker stop wishop-app-api && sudo docker rm wishop-app-api && sudo docker rmi huag1234/wishop-app-api:$API_TAG && sudo docker pull huag1234/wishop-app-api:$API_TAG && sudo docker run --name wishop-app-api -p 3000:3000 -d huag1234/wishop-app-api:$API_TAG && exit"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy-to-dev:
          requires:
            - build
          filters:
            branches:
                only: develop